namespace AttendanceApp.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<AttendanceApp.AttendanceContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
        }

        protected override void Seed(AttendanceApp.AttendanceContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //

            context.Teachers.AddOrUpdate(
                f => f.FirstName, 
                new Teachers() { FirstName = "Chin", LastName = "Carignan", Password = "123", UserName = "chin" },
                new Teachers() { FirstName = "Eve", LastName = "Elsey", Password = "123", UserName = "eve" },
                new Teachers() { FirstName = "Priscilla", LastName = "Pence", Password = "123", UserName = "priscilla" },
                new Teachers() { FirstName = "Elli", LastName = "Kensey", Password = "123", UserName = "elli" },
                new Teachers() { FirstName = "Kali", LastName = "Ehrlich", Password = "123", UserName = "kali" }

                );
            context.Students.AddOrUpdate(
                s => s.FirstName,
                new Students() { FirstName="Candie" , LastName="Drayton", Password="123"},
                new Students() { FirstName="Gaylene" , LastName="Peloquin", Password="123"},
                new Students() { FirstName="Florencio" , LastName="Gorney", Password="123"},
                new Students() { FirstName="Eric" , LastName="Strum", Password="123"},
                new Students() { FirstName="Elfriede" , LastName="Heimann", Password="123"},
                new Students() { FirstName="Glenn" , LastName="Parrent", Password="123"},
                new Students() { FirstName="Sunday" , LastName="Polansky", Password="123"},
                new Students() { FirstName="Elroy" , LastName="Sedillo", Password="123"},
                new Students() { FirstName="Francoise" , LastName="Knisley", Password="123"},
                new Students() { FirstName="Myesha" , LastName="Kamm", Password="123"},
                new Students() { FirstName="Tad" , LastName="Mizell", Password="123"},
                new Students() { FirstName="Cherie" , LastName="Wittrock", Password="123"},
                new Students() { FirstName="Elda" , LastName="Lagunas", Password="123"},
                new Students() { FirstName="Sheryll" , LastName="Salido", Password="123"},
                new Students() { FirstName="Jenny" , LastName="Carlsen", Password="123"},
                new Students() { FirstName="Milford" , LastName="Seagraves", Password="123"},
                new Students() { FirstName="Tashina" , LastName="Holzman", Password="123"},
                new Students() { FirstName="Sanjuana" , LastName="Acker", Password="123"},
                new Students() { FirstName="Edward" , LastName="Paugh", Password="123"},
                new Students() { FirstName="Antonina" , LastName="Capra", Password="123"},
                new Students() { FirstName="Babette" , LastName="Saum", Password="123"},
                new Students() { FirstName="Kathey" , LastName="Sylva", Password="123"},
                new Students() { FirstName="Tami" , LastName="Raya", Password="123"},
                new Students() { FirstName="Tifany" , LastName="Basso", Password="123"},
                new Students() { FirstName="Sherrill" , LastName="Brandenburg", Password="123"},
                new Students() { FirstName="Francesca" , LastName="Samms", Password="123"},
                new Students() { FirstName="Humberto" , LastName="Paulhus", Password="123"},
                new Students() { FirstName="Taisha" , LastName="Dollison", Password="123"},
                new Students() { FirstName="Tayna" , LastName="Elie", Password="123"},
                new Students() { FirstName="Jodee" , LastName="Sampsel", Password="123"},
                new Students() { FirstName="Karyl" , LastName="Thiry", Password="123"},
                new Students() { FirstName="Chuck" , LastName="Sumrall", Password="123"},
                new Students() { FirstName="Leisha" , LastName="Creighton", Password="123"},
                new Students() { FirstName="Irish" , LastName="Hayashida", Password="123"},
                new Students() { FirstName="Cammie" , LastName="Pasquale", Password="123"},
                new Students() { FirstName="Lanelle" , LastName="Marx", Password="123"},
                new Students() { FirstName="Gregoria" , LastName="Gilmartin", Password="123"},
                new Students() { FirstName="Keneth" , LastName="Alva", Password="123"},
                new Students() { FirstName="Debra" , LastName="Elizalde", Password="123"},
                new Students() { FirstName="Willow" , LastName="Baro", Password="123"},
                new Students() { FirstName="Vannessa" , LastName="Housand", Password="123"},
                new Students() { FirstName="Jackie" , LastName="Diamond", Password="123"},
                new Students() { FirstName="Rikki" , LastName="Deleo", Password="123"},
                new Students() { FirstName="Cory" , LastName="Guimond", Password="123"},
                new Students() { FirstName="Jada" , LastName="Charters", Password="123"},
                new Students() { FirstName="Tajuana" , LastName="Macleod", Password="123"},
                new Students() { FirstName="Zelma" , LastName="Danielsen", Password="123"},
                new Students() { FirstName="Ilda" , LastName="Bryce", Password="123"},
                new Students() { FirstName="Henrietta" , LastName="Ocegueda", Password="123"},
                new Students() { FirstName="Lianne" , LastName="Greenway", Password="123"}
                );


            context.Classes.AddOrUpdate(
                c => c.ClassName,
                new Classes() { ClassName = "Biologi", TeacherId = 1 },
                new Classes() { ClassName = "Mattematik A", TeacherId = 2 },
                new Classes() { ClassName = "Mattematik B", TeacherId = 2 },
                new Classes() { ClassName = "Mattematik C", TeacherId = 2 },
                new Classes() { ClassName = "Programmering A", TeacherId = 5 },
                new Classes() { ClassName = "Programmering B", TeacherId = 5 },
                new Classes() { ClassName = "Träslöjd", TeacherId = 3 },
                new Classes() { ClassName = "Musik", TeacherId = 3 },
                new Classes() { ClassName = "Natuvetenskap", TeacherId = 4 },
                new Classes() { ClassName = "Fysik A", TeacherId = 1 },
                new Classes() { ClassName = "Fysik B", TeacherId = 1 },
                new Classes() { ClassName = "Hemkunskap", TeacherId = 3 }
                );

            context.Enrolled.AddOrUpdate(
               e => e.StudentId,
                new Enrolled() { StudentId = 1, ClassId = 1 },
                new Enrolled() { StudentId = 1, ClassId = 2 },
                new Enrolled() { StudentId = 1, ClassId = 5 },
                new Enrolled() { StudentId = 1, ClassId = 7 },
                new Enrolled() { StudentId = 1, ClassId = 1 },
                new Enrolled() { StudentId = 1, ClassId = 12 },
                new Enrolled() { StudentId = 2, ClassId = 1 },
                new Enrolled() { StudentId = 2, ClassId = 2 },
                new Enrolled() { StudentId = 2, ClassId = 5 },
                new Enrolled() { StudentId = 2, ClassId = 7 },
                new Enrolled() { StudentId = 2, ClassId = 1 },
                new Enrolled() { StudentId = 2, ClassId = 12 },
                new Enrolled() { StudentId = 3, ClassId = 1 },
                new Enrolled() { StudentId = 3, ClassId = 2 },
                new Enrolled() { StudentId = 3, ClassId = 5 },
                new Enrolled() { StudentId = 3, ClassId = 7 },
                new Enrolled() { StudentId = 3, ClassId = 1 },
                new Enrolled() { StudentId = 3, ClassId = 12 },
                new Enrolled() { StudentId = 4, ClassId = 1 },
                new Enrolled() { StudentId = 4, ClassId = 2 },
                new Enrolled() { StudentId = 4, ClassId = 5 },
                new Enrolled() { StudentId = 4, ClassId = 7 },
                new Enrolled() { StudentId = 4, ClassId = 1 },
                new Enrolled() { StudentId = 4, ClassId = 12 },
                new Enrolled() { StudentId = 5, ClassId = 1 },
                new Enrolled() { StudentId = 5, ClassId = 2 },
                new Enrolled() { StudentId = 5, ClassId = 5 },
                new Enrolled() { StudentId = 5, ClassId = 7 },
                new Enrolled() { StudentId = 5, ClassId = 1 },
                new Enrolled() { StudentId = 5, ClassId = 12 },
                new Enrolled() { StudentId = 6, ClassId = 1 },
                new Enrolled() { StudentId = 6, ClassId = 2 },
                new Enrolled() { StudentId = 6, ClassId = 5 },
                new Enrolled() { StudentId = 6, ClassId = 7 },
                new Enrolled() { StudentId = 6, ClassId = 1 },
                new Enrolled() { StudentId = 6, ClassId = 12 },
                new Enrolled() { StudentId = 7, ClassId = 1 },
                new Enrolled() { StudentId = 7, ClassId = 2 },
                new Enrolled() { StudentId = 7, ClassId = 5 },
                new Enrolled() { StudentId = 7, ClassId = 7 },
                new Enrolled() { StudentId = 7, ClassId = 1 },
                new Enrolled() { StudentId = 7, ClassId = 12 },
                new Enrolled() { StudentId = 8, ClassId = 1 },
                new Enrolled() { StudentId = 8, ClassId = 2 },
                new Enrolled() { StudentId = 8, ClassId = 5 },
                new Enrolled() { StudentId = 8, ClassId = 7 },
                new Enrolled() { StudentId = 8, ClassId = 1 },
                new Enrolled() { StudentId = 8, ClassId = 12 },
                new Enrolled() { StudentId = 9, ClassId = 1 },
                new Enrolled() { StudentId = 9, ClassId = 2 },
                new Enrolled() { StudentId = 9, ClassId = 5 },
                new Enrolled() { StudentId = 9, ClassId = 7 },
                new Enrolled() { StudentId = 9, ClassId = 1 },
                new Enrolled() { StudentId = 9, ClassId = 12 },
                new Enrolled() { StudentId = 10, ClassId = 1 },
                new Enrolled() { StudentId = 10, ClassId = 2 },
                new Enrolled() { StudentId = 10, ClassId = 5 },
                new Enrolled() { StudentId = 10, ClassId = 7 },
                new Enrolled() { StudentId = 10, ClassId = 1 },
                new Enrolled() { StudentId = 10, ClassId = 12 },
                new Enrolled() { StudentId = 11, ClassId = 3 },
                new Enrolled() { StudentId = 11, ClassId = 6 },
                new Enrolled() { StudentId = 11, ClassId = 9 },
                new Enrolled() { StudentId = 11, ClassId = 11 },
                new Enrolled() { StudentId = 12, ClassId = 3 },
                new Enrolled() { StudentId = 12, ClassId = 6 },
                new Enrolled() { StudentId = 12, ClassId = 9 },
                new Enrolled() { StudentId = 12, ClassId = 11 },
                new Enrolled() { StudentId = 13, ClassId = 3 },
                new Enrolled() { StudentId = 13, ClassId = 6 },
                new Enrolled() { StudentId = 13, ClassId = 9 },
                new Enrolled() { StudentId = 13, ClassId = 11 },
                new Enrolled() { StudentId = 14, ClassId = 3 },
                new Enrolled() { StudentId = 14, ClassId = 6 },
                new Enrolled() { StudentId = 14, ClassId = 9 },
                new Enrolled() { StudentId = 14, ClassId = 11 },
                new Enrolled() { StudentId = 15, ClassId = 3 },
                new Enrolled() { StudentId = 15, ClassId = 6 },
                new Enrolled() { StudentId = 15, ClassId = 9 },
                new Enrolled() { StudentId = 15, ClassId = 11 },
                new Enrolled() { StudentId = 16, ClassId = 3 },
                new Enrolled() { StudentId = 16, ClassId = 6 },
                new Enrolled() { StudentId = 16, ClassId = 9 },
                new Enrolled() { StudentId = 16, ClassId = 11 },
                new Enrolled() { StudentId = 17, ClassId = 3 },
                new Enrolled() { StudentId = 17, ClassId = 6 },
                new Enrolled() { StudentId = 17, ClassId = 9 },
                new Enrolled() { StudentId = 17, ClassId = 11 },
                new Enrolled() { StudentId = 18, ClassId = 3 },
                new Enrolled() { StudentId = 18, ClassId = 6 },
                new Enrolled() { StudentId = 18, ClassId = 9 },
                new Enrolled() { StudentId = 18, ClassId = 11 },
                new Enrolled() { StudentId = 19, ClassId = 3 },
                new Enrolled() { StudentId = 19, ClassId = 6 },
                new Enrolled() { StudentId = 19, ClassId = 9 },
                new Enrolled() { StudentId = 19, ClassId = 11 },
                new Enrolled() { StudentId = 20, ClassId = 3 },
                new Enrolled() { StudentId = 20, ClassId = 6 },
                new Enrolled() { StudentId = 20, ClassId = 9 },
                new Enrolled() { StudentId = 20, ClassId = 11 },
                new Enrolled() { StudentId = 21, ClassId = 4 },
                new Enrolled() { StudentId = 21, ClassId = 8 },
                new Enrolled() { StudentId = 21, ClassId = 9 },
                new Enrolled() { StudentId = 21, ClassId = 11 },
                new Enrolled() { StudentId = 21, ClassId = 6 },
                new Enrolled() { StudentId = 22, ClassId = 4 },
                new Enrolled() { StudentId = 22, ClassId = 8 },
                new Enrolled() { StudentId = 22, ClassId = 9 },
                new Enrolled() { StudentId = 22, ClassId = 11 },
                new Enrolled() { StudentId = 22, ClassId = 6 },
                new Enrolled() { StudentId = 23, ClassId = 4 },
                new Enrolled() { StudentId = 23, ClassId = 8 },
                new Enrolled() { StudentId = 23, ClassId = 9 },
                new Enrolled() { StudentId = 23, ClassId = 11 },
                new Enrolled() { StudentId = 23, ClassId = 6 },
                new Enrolled() { StudentId = 24, ClassId = 4 },
                new Enrolled() { StudentId = 24, ClassId = 8 },
                new Enrolled() { StudentId = 24, ClassId = 9 },
                new Enrolled() { StudentId = 24, ClassId = 11 },
                new Enrolled() { StudentId = 24, ClassId = 6 },
                new Enrolled() { StudentId = 25, ClassId = 4 },
                new Enrolled() { StudentId = 25, ClassId = 8 },
                new Enrolled() { StudentId = 25, ClassId = 9 },
                new Enrolled() { StudentId = 25, ClassId = 11 },
                new Enrolled() { StudentId = 25, ClassId = 6 },
                new Enrolled() { StudentId = 26, ClassId = 4 },
                new Enrolled() { StudentId = 26, ClassId = 8 },
                new Enrolled() { StudentId = 26, ClassId = 9 },
                new Enrolled() { StudentId = 26, ClassId = 11 },
                new Enrolled() { StudentId = 26, ClassId = 6 },
                new Enrolled() { StudentId = 27, ClassId = 4 },
                new Enrolled() { StudentId = 27, ClassId = 8 },
                new Enrolled() { StudentId = 27, ClassId = 9 },
                new Enrolled() { StudentId = 27, ClassId = 11 },
                new Enrolled() { StudentId = 27, ClassId = 6 },
                new Enrolled() { StudentId = 28, ClassId = 4 },
                new Enrolled() { StudentId = 28, ClassId = 8 },
                new Enrolled() { StudentId = 28, ClassId = 9 },
                new Enrolled() { StudentId = 28, ClassId = 11 },
                new Enrolled() { StudentId = 28, ClassId = 6 },
                new Enrolled() { StudentId = 29, ClassId = 4 },
                new Enrolled() { StudentId = 29, ClassId = 8 },
                new Enrolled() { StudentId = 29, ClassId = 9 },
                new Enrolled() { StudentId = 29, ClassId = 11 },
                new Enrolled() { StudentId = 29, ClassId = 6 },
                new Enrolled() { StudentId = 30, ClassId = 4 },
                new Enrolled() { StudentId = 30, ClassId = 8 },
                new Enrolled() { StudentId = 30, ClassId = 9 },
                new Enrolled() { StudentId = 30, ClassId = 11 },
                new Enrolled() { StudentId = 30, ClassId = 6 }
               );
        }
    }
}
